### ISSUE TITLE
В выводе внешнего блока объекта недвижимости фотки - верстка

### ISSUE THREAD

**Issue by kindcasper** [dualavatara/jbfw#61]
В выводе внешнего блока объекта недвижимости большая фотка и остальные маленькие по нижнему краю находятся не на одной линии!

**Comment by dualavatara** [comment]
Без скрина не понятно о чем речь.

**Comment by kindcasper** [comment]
По верстке позже сразу пачкой дизайнер обещала дать! Или лучше по мере нахождения ?
