### ISSUE TITLE
Создать почтовые ящики

### ISSUE THREAD

**Issue by kindcasper** [dualavatara/jbfw#64]
info@JB-Travel.com
office@JB-Travel.com

**Comment by dualavatara** [comment]
Хостить почту у себя редкостный гемор по ряду причин:
1. Блэклисты. По опыту админства почтового сервака это главная головная боль. Сервак в них постоянно попадает каким-то волшебным образом даже если пол года почта ходила фактически внутри него.
2. Релеинг. Затыкать дыры в почтовом сервисе - постоянная и нудная работа. Чуть пустил на самотек - см. п.1
3. Место на диске, переезд на другой хостинг и еще куча других моментов.

Резюме: очень предлагаю пользоваться гугловским сервисом, типа вот http://www.google.com/apps/intl/en/group/index.html

**Comment by kindcasper** [comment]
Согласен, а как сделать ?

**Comment by dualavatara** [comment]
Сделал. Логин на http://gmail.com
login: kindcasper@jb-travel.com
password: Lj,hsqRfcgth
info@jb-travel.com и office@jb-travel.com сделал как группы пока, в группы тебя добавил
