### ISSUE TITLE
Во внешнем списке при клике на мал. картинку неправильно отрабатывает

### ISSUE THREAD

**Issue by kindcasper** [dualavatara/jbfw#83]
Во внешнем списке при клике на мал. картинку неправильно отрабатывает: оно открывается в этом же окне, а нужно чтобы запускалось в просмоторщике как и внутри объекта
Также нету предпросмотра ри наведении.

**Comment by dualavatara** [comment]
Внешний список - это что? Дим, скрины прикладывай пожалуйста по возможности везде, не всегда понятно о чем речь.

**Comment by kindcasper** [comment]
Это старый баг, сейчас все ок
